site_name: Docs
site_author: Kai Zhang
site_url: https://kaizhang-shanxi.github.io/docs

repo_name: GitHub
repo_url: https://github.com/kaizhang-shanxi/docs

copyright: Copyright &copy; 2017 Kai Zhang

theme: "material"

extra:
  social:
    - type: "github"
      link: "https://github.com/kaizhang-shanxi"

markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - footnotes
  - toc(permalink=true)
  - pymdownx.tasklist(custom_checkbox=true)

pages:
  - Home: index.md
  - Arch Linux: Arch-Linux.md
